name: iflow
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py310h06a4308_0
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.1=py310h9ce1e76_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - pillow=9.0.1=py310h22f2fdc_0
  - pip=22.2.2=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py310h06a4308_0
  - setuptools=65.5.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.3.0=py310h06a4308_0
  - tzdata=2022f=h04d1e81_0
  - urllib3=1.26.12=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - cuda=11.6.2=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.6.2=0
  - cuda-libraries-dev=11.6.2=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=11.8.87=0
  - cuda-runtime=11.6.2=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.6.2=0
  - cuda-tools=11.6.2=0
  - cuda-visual-tools=11.6.2=0
  - gds-tools=1.4.0.31=0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - nsight-compute=2022.3.0.22=0
  - ffmpeg=4.3=hf484d3e_0
  - pytorch=1.13.0=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_0
  - pytorch-mutex=1.0=cuda
  - torchvision=0.14.0=py310_cu116
  - pip:
    - contourpy==1.0.6
    - cycler==0.11.0
    - fonttools==4.38.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.2
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.5.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - torch==1.13.0

